version: "3"

services:
  postgres:
    image: "postgres:12.2-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
  server:
    build:
      context: ".."
      args:
        PACKAGE: "graphql-server"
    command: "graphql-server"
    depends_on:
      - "postgres"
    environment:
      ADDR: "0.0.0.0:3000"
      DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"
    ports:
      - "3000:3000"
